[package]
name = "timecat"
authors = ["Gourab Ghosh"]
version = "1.1.0"
edition = "2021"
homepage = "https://github.com/Gourab-Ghosh/timecat-rs/"
repository = "https://github.com/Gourab-Ghosh/timecat-rs/"
description = "A NNUE based chess engine implementing the Negamax algorithm."
license-file = "LICENSE"
# keywords = ["rust", "chess-engine", "chess", "uci", "alpha-beta-pruning", "negamax", "chess-ai", "uci-chess-engine", "nnue", "timecat", "timecat-rs"]
keywords = ["engine", "chess", "uci", "nnue", "ai"]
readme = "README.md"
include = [
    "src/",
    "!src/**/*.bak",
    "build.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
lto = true
panic = "abort"
# rustflags = ["-C", "target-cpu=native"]
# strip = true

[dependencies]
arrayvec = "0.*"
binread = { version = "2.2.0", features = ["const_generics"] }
bytemuck = { version = "1.14.3", features = ["min_const_generics", "derive", "extern_crate_alloc"] }
colored = "2.*"
failure = "0.*"
itertools = "0.*"
lazy_static = "1.*"
paste = "1.*"
serde = { version = "1.*", features = ["derive"], optional = true }

[build-dependencies]
reqwest = { version = "0.*", features = ["blocking"] }
sha256 = "1.*"

[features]
# default = ["serde"]
serde = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true
