[package]
name = "timecat"
authors = ["Gourab Ghosh"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Gourab-Ghosh/timecat-rs/"
description = "A chess engine"
license-file = "LICENSE"
keywords = ["rust", "chess-engine", "chess", "uci", "alpha-beta-pruning", "negamax", "chess-ai", "uci-chess-engine", "nnue", "timecat", "timecat-rs"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
lto = true
panic = "abort"
# rustflags = ["-C", "target-cpu=native"]
# strip = true

[dependencies]
binread = { version = "2.2.0", features = ["const_generics"] }
bytemuck = { version = "1.13.1", features = ["min_const_generics", "derive", "extern_crate_alloc"] }
chess = "3.2.0"
colored = "2.0.4"
failure = "0.1.8"
fxhash = "0.2.1"
itertools = "0.11.0"
lazy_static = "1.4.0"

[build-dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }
sha256 = "1.4.0"

[package.metadata.docs.rs]
all-features = true
